version: "3.9"

services:
  mysql:
    build: ./mysql/
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
